# Feature Engineering

### Import Libraries

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

### Load Preprocessed Dataset

In [3]:
df = pd.read_csv("../data/preprocessed_news.csv")
df.head()

,content,label,processed_content
0,Many 'lost' voters say they have found their c...,1,mani lost voter say found candid trump washing...
1,"Iranian Revolutionary Guards commander, anothe...",1,iranian revolutionari guard command anoth figh...
2,Cambodian leader gets China's backing as West ...,1,cambodian leader get china back west condemn c...
3,Ex-KKK Grand Wizard: Maine Gov. Right To Call...,0,ex kkk grand wizard main gov right call black ...
4,FINGER-WAGGING GRANNY HILLARY CLINTON Blows Up...,0,finger wag granni hillari clinton blow activis...

In [4]:
x = df["processed_content"]
y = df["label"]

### Apply TF-IDF and convert to Dataframe

In [5]:
vectorizer = TfidfVectorizer(max_features=5000)

In [6]:
x_tfidf = vectorizer.fit_transform(x)

In [7]:
print(x_tfidf.shape)

(39105, 5000)

In [8]:
x_df = pd.DataFrame(x_tfidf.toarray())
x_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Save Features

In [9]:
x_df.to_csv("../data/x_features.csv", index=False)
y.to_csv("../data/y_labels.csv", index=False)
print("Feature Extraction completed and saved!")

Feature Extraction completed and saved!